ALTER TYPE "ProductCategory" ADD VALUE IF NOT EXISTS 'ACCESSORIES';
ALTER TYPE "ProductCategory" ADD VALUE IF NOT EXISTS 'DECORATION_GIFTS';
ALTER TYPE "ProductCategory" ADD VALUE IF NOT EXISTS 'CARE_STORAGE';
ALTER TYPE "ProductCategory" ADD VALUE IF NOT EXISTS 'OFFERS';
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "subcategory" TEXT;
